### ISSUE TITLE
It does nothing after Enter

### ISSUE THREAD

**Issue by sambt22022517** [VermiIIi0n/fuckBookWalker#3]
I've run base on your guide at README, but after 1 hour, nothing happened except the line `could not detect version_main.therefore, we are assuming it is chrome 108 or higher`.
This is my command: `poetry run python bookphucker https://bookwalker.jp/de99571adf-73d3-4b0a-9384-08c8ecbcc189/`
Then, it occurs and nothing else comes after 1 hour:
![image](https://github.com/VermiIIi0n/fuckBookWalker/assets/120190847/d309148f-cff5-4611-970a-a501955e3583)

I've pressed `Ctrl + C` to break and this is:
![image](https://github.com/VermiIIi0n/fuckBookWalker/assets/120190847/4da57d6b-4c95-4e75-a290-8342f3897545)

I've try to download chromedriver 114 win 32 from [this link](https://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/) and put the `chromedriver.exe` at the same folder with `config.json`, but the error is not solved.

The line `could not detect version_main.therefore, we are assuming it is chrome 108 or higher` is exactly like your example image. So must i wait for a longer time than 1 hour ?

**Comment by VermiIIi0n** [comment]
That's definitely abnormal, I've just tested this script and it's still working for me, so I cannot reproduce your issue.

Please set `headless` in your config file to `false` to examine where it gets stuck.
That may also be an upstream issue, perhaps you can try ubuntu subsystems in Microsoft app store. 

Normally the script should've at least thrown a timeout error instead of wasting an hour of yours, i'm sorry for your loss of time🫠.

**Comment by sambt22022517** [comment]
Set `headless = false` has solved my issue. But it can't download. Must i buy that light novel before downloading ? Cuz there is a image `error.png` appear in my folder.
